from selenium.webdriver import Chrome

driver = Chrome('C:\AllPythonProjects\PythonLearning\learning\driver\chromedriver.exe')
size = driver.get_window_size()
print('size = ',size)
position = driver.get_window_position()
print('position = ',position)
driver.maximize_window()
size = driver.get_window_size()
print('size = ',size)
position = driver.get_window_position()
print('position = ',position)
driver.minimize_window()
size = driver.get_window_size()
print('size = ',size)
position = driver.get_window_position()
print('position = ',position)
driver.get('https://www.gmail.com')
print('Open Browser')
url = list()
url.append(driver.current_url)
driver.get('http://www.google.com')
url.append(driver.current_url)
driver.get('https://www.gmail.com')
url.append(driver.current_url)
title = driver.title
print(title)
cookies = driver.get_cookies()
print('cookies = ', cookies)
driver.delete_all_cookies()
cookies = driver.get_cookies()
print('cookies = ', cookies)
driver.set_window_position(x=20,y=20)
print(driver.set_window_position(x=20,y=20))
#driver.quit()            # close and quit will work only on current session browser instance
#driver.close()           # close will always close current session browser window
                         # quit will close all the browser window which are opened in current seesion
print(url)
for i in url:
    print(i)
